a=int(input("dati numarul de oua pentru gaina 1 intr-o zi"))
b=int(input("dati numarul de oua pentru gaina 2 intr-o zi"))
c=int(input("dati numarul de oua pentru gaina 3 intr-o zi"))
d=int(input("dati numarul de oua peina 4 intr-o zi"))
print("intr-o saptamana se obtin",(a*7)+(b*7)+(c*7)+(d*7),"oua")